"""
M2 — Large-broker concentration (validation only).

Specified metric (from Decisions/EH&B/Brokerage Metrics.xlsx Core metrics
and chtr-ehb-broker-channel-core-metrics.canvas.tsx):

  Numerator: covered lives at the top N broker firms (e.g. top 5 / top 10)
  Denominator: total broker-placed covered lives in the same geography
  Unit: percent

This script does not invent a lives share. It recomputes retrieved *revenue*
and *compensation* proxies, tags origin, and writes the unknown remainder
(lives; Spectrum-state cut; firms below the ranking).

No TAM. No launch recommendation.
"""
from __future__ import annotations

import csv
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent
OUT = ROOT / "out"
OUT.mkdir(parents=True, exist_ok=True)

# --- Business Insurance 2025 ranking of 2024 U.S. brokerage revenue ----------
# Source: BI survey, ranked by 2024 brokerage revenue generated by U.S.-based
# clients. Companies with >49% of gross revenue from personal lines excluded.
# PDF: https://communityprod.blob.core.windows.net/public/top_100_2025_bi.pdf
# Funded by: Business Insurance / Crain Communications (trade press; brokers
# self-report). THIS IS REVENUE, NOT COVERED LIVES. Mixes P&C + benefits.

BI_TOP10 = [
    (1, "Marsh McLennan Cos. Inc.", 12_665_500_000, "Pro forma McGriff (closed 15 Nov 2024)"),
    (2, "Aon PLC", 7_497_381_760, "Pro forma NFP (acquired 24 Apr 2024); 2023 restated"),
    (3, "Arthur J. Gallagher & Co.", 7_092_288_000, "2023 restated; AssuredPartners not in this 2024 year"),
    (4, "Willis Towers Watson PLC", 5_064_280_000, ""),
    (5, "Alliant Insurance Services Inc.", 4_969_605_524, "2023 restated"),
    (6, "Brown & Brown Inc.", 4_036_781_833, ""),
    (7, "Hub International Ltd.", 3_814_376_800, ""),
    (8, "Lockton Cos. LLC", 2_874_818_840, "Fiscal year ending 30 Apr"),
    (9, "AssuredPartners Inc.", 2_809_791_938, "Later acquired by Gallagher (2025); 2023 restated"),
    (10, "USI Insurance Services LLC", 2_786_726_700, ""),
]

# Ranks 11–100, same PDF, USD. Names not needed for the Top 100 total.
BI_11_TO_100 = [
    2_727_332_438, 1_737_405_200, 1_696_546_641, 1_432_000_000, 1_386_222_000,
    1_237_900_000, 1_035_329_776, 908_000_000, 905_023_000, 816_820_210,
    691_000_000, 641_000_000, 564_000_000, 556_419_632, 555_869_000,
    511_046_000, 363_194_400, 357_569_512, 346_238_000, 339_200_000,
    326_810_000, 323_950_561, 315_000_000, 307_145_000, 282_358_414,
    266_552_000, 235_200_000, 233_747_187, 224_075_725, 209_968_520,
    191_534_640, 190_388_817, 180_500_000, 177_320_191, 165_000_000,
    136_433_118, 130_008_021, 128_686_834, 127_884_010, 122_978_000,
    117_846_123, 117_515_600, 115_569_153, 112_115_275, 108_743_052,
    104_404_080, 96_909_271, 91_881_396, 91_094_695, 86_682_400,
    73_328_000, 71_434_000, 67_842_008, 67_641_412, 67_624_107,
    67_596_012, 67_583_607, 66_772_977, 66_180_838, 65_936_742,
    64_572_483, 62_316_704, 61_944_499, 59_227_205, 57_491_609,
    55_343_027, 54_948_589, 54_026_784, 52_839_832, 51_226_440,
    50_468_672, 50_436_000, 48_917_767, 48_100_000, 47_493_220,
    46_344_700, 43_401_906, 43_344_790, 41_232_416, 40_227_256,
    40_167_000, 39_704_428, 39_611_000, 38_133_328, 35_014_130,
    34_149_000, 31_606_952, 30_962_097, 29_744_970, 28_860_720,
]

BI_ALL = [r[2] for r in BI_TOP10] + BI_11_TO_100
assert len(BI_ALL) == 100, len(BI_ALL)

BI_TOP5_USD = sum(BI_ALL[:5])
BI_TOP10_USD = sum(BI_ALL[:10])
BI_TOP100_USD = sum(BI_ALL)
BI_NAMED_USD = (  # Marsh + Aon (NFP inside) + Gallagher + WTW + Lockton
    BI_ALL[0] + BI_ALL[1] + BI_ALL[2] + BI_ALL[3] + BI_ALL[7]
)
BI_TOP5_PCT = 100.0 * BI_TOP5_USD / BI_TOP100_USD
BI_TOP10_PCT = 100.0 * BI_TOP10_USD / BI_TOP100_USD
BI_NAMED_PCT = 100.0 * BI_NAMED_USD / BI_TOP100_USD

# MarshBerry citing the *next* BI vintage (2025 U.S. revenue, published 2026).
# Different year from the PDF above. Do not mix.
MARSHBERRY_TOP100_USD = 83.3e9
MARSHBERRY_TOP10_USD = 58.5e9
MARSHBERRY_TOP10_PCT = 100.0 * MARSHBERRY_TOP10_USD / MARSHBERRY_TOP100_USD  # 70.2 → they state 70%

# --- PlanOptica Form 5500 health & welfare broker compensation ---------------
# Ranked by total compensation; published "market share" column.
# Source filings: DOL/EBSA Form 5500 Schedule A / C, ingested by PlanOptica.
# THIS IS COMPENSATION, NOT COVERED LIVES. Entity names are filing names
# (MMA and Mercer listed separately; Hub Midwest not all of Hub).
# 1–25 of 43,129 names on the public table.

PLANOPTICA = [
    ("MARSH & MCLENNAN AGENCY LLC", 804.5e6, 31.68e9, 12206, 7.1),
    ("GALLAGHER BENEFIT SERVICES, INC.", 675.7e6, 24.36e9, 10070, 5.9),
    ("LOCKTON COMPANIES, LLC", 661.7e6, 22.06e9, 6759, 5.8),
    ("MERCER HEALTH AND BENEFITS, LLC", 573.0e6, 18.73e9, 4846, 5.0),
    ("USI INSURANCE SERVICES LLC", 494.1e6, 16.67e9, 9879, 4.3),
    ("WILLIS TOWERS WATSON US LLC", 485.3e6, 17.15e9, 5208, 4.3),
    ("HUB INTERNATIONAL MIDWEST LIMITED", 472.2e6, 21.29e9, 7297, 4.1),
    ("AON CONSULTING INC", 322.9e6, 13.89e9, 3147, 2.8),
    ("ALLIANT INSURANCE SERVICES, INC.", 286.5e6, 9.32e9, 3621, 2.5),
    ("BROWN & BROWN INSURANCE SERVICES", 246.8e6, 21.94e9, 4784, 2.2),
]
NFP_SHARE_PCT = 1.6  # NFP INSURANCE SERVICES INC, still listed separately
PO_TOP5_PCT = round(sum(r[4] for r in PLANOPTICA[:5]), 1)
PO_TOP10_PCT = round(sum(r[4] for r in PLANOPTICA), 1)
PO_TAIL_PCT = round(100.0 - PO_TOP10_PCT, 1)
PO_MARSH_ROLLUP_PCT = round(PLANOPTICA[0][4] + PLANOPTICA[3][4], 1)  # MMA + Mercer
PO_NAMED_PCT = round(  # Marsh rollup + Gallagher + Lockton + WTW + Aon + NFP
    PO_MARSH_ROLLUP_PCT
    + PLANOPTICA[1][4]
    + PLANOPTICA[2][4]
    + PLANOPTICA[5][4]
    + PLANOPTICA[7][4]
    + NFP_SHARE_PCT,
    1,
)
PO_BROKER_COUNT = 43129

# Implied compensation universe from MMA published share (rounding check only).
PO_IMPLIED_TOTAL_USD = PLANOPTICA[0][1] / (PLANOPTICA[0][4] / 100.0)
PO_TOP10_USD = sum(r[1] for r in PLANOPTICA)
PO_TOP10_PCT_FROM_DOLLARS = 100.0 * PO_TOP10_USD / PO_IMPLIED_TOTAL_USD

# --- 10-K line items (revenue, not lives) ------------------------------------
MMC_2024_REVENUE_USD = 24_458e6
MMC_MERCER_PCT = 23.0  # "approximately 23%" of company revenue
MMC_MARSH_PCT = 53.0
MMC_MERCER_USD = MMC_2024_REVENUE_USD * (MMC_MERCER_PCT / 100.0)
AON_HEALTH_SOLUTIONS_2024_USD = 3_335e6  # global; includes Talent and NFP
AJG_US_MIX_PCT = 64.0  # of combined brokerage + risk-management revenue
WTW_HWC_PCT = 59.0  # Health, Wealth & Career; Health & Benefits not broken out

# KFF / Mark Farrah: broker fees PMPM by market, 2024. Not firm concentration.
KFF_SMALL_GROUP_PMPM = 29.79
KFF_LARGE_GROUP_PMPM = 10.00

assert abs(PO_TOP5_PCT - 28.1) < 0.05
assert abs(PO_TOP10_PCT - 44.0) < 0.05
assert abs(PO_TAIL_PCT - 56.0) < 0.05
assert abs(PO_NAMED_PCT - 32.5) < 0.05
assert abs(BI_TOP10_PCT - 67.181) < 0.02


def write_csv(path: pathlib.Path, fieldnames: list[str], rows: list[dict]) -> None:
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)


def main() -> None:
    bi_rows = []
    for rank, name, usd, note in BI_TOP10:
        bi_rows.append(
            {
                "rank": rank,
                "company": name,
                "us_brokerage_revenue_usd": usd,
                "share_of_top100_pct": round(100.0 * usd / BI_TOP100_USD, 2),
                "unit": "2024 U.S. brokerage revenue (not lives)",
                "note": note,
            }
        )
    write_csv(
        OUT / "bi_top10_us_brokerage_revenue_2024.csv",
        ["rank", "company", "us_brokerage_revenue_usd", "share_of_top100_pct", "unit", "note"],
        bi_rows,
    )

    po_rows = []
    for name, comp, premium, sponsors, share in PLANOPTICA:
        po_rows.append(
            {
                "filing_name": name,
                "compensation_usd": comp,
                "premium_overseen_usd": premium,
                "sponsors": sponsors,
                "published_market_share_pct": share,
                "unit": "Form 5500 health & welfare compensation (not lives)",
            }
        )
    write_csv(
        OUT / "planoptica_top10_ehb_compensation.csv",
        [
            "filing_name",
            "compensation_usd",
            "premium_overseen_usd",
            "sponsors",
            "published_market_share_pct",
            "unit",
        ],
        po_rows,
    )

    register = [
        {
            "line_id": "S1",
            "description": "M2 specified numerator",
            "value": "covered lives at top N broker firms (N e.g. 5 or 10, not locked)",
            "unit": "lives",
            "origin": "DEFINITION",
            "funded_by": "n/a — metric register",
            "url": "Decisions/EH&B/Brokerage Metrics.xlsx (Core metrics, M2)",
            "notes": "Same definition on chtr-ehb-broker-channel-core-metrics.canvas.tsx",
        },
        {
            "line_id": "S2",
            "description": "M2 specified denominator",
            "value": "total broker-placed covered lives in the same geography as M1",
            "unit": "lives",
            "origin": "DEFINITION",
            "funded_by": "n/a — metric register",
            "url": "Decisions/EH&B/Brokerage Metrics.xlsx (Core metrics, M2)",
            "notes": "Geography is Spectrum-state book in M1, not independently specified as US",
        },
        {
            "line_id": "X1",
            "description": "Share of broker-placed EH&B covered lives at largest N brokers",
            "value": "",
            "unit": "percent of lives",
            "origin": "NOT RETRIEVED",
            "funded_by": "n/a",
            "url": "",
            "notes": "Refused to invent. 10-Ks do not disclose US EH&B covered lives or lives share.",
        },
        {
            "line_id": "A1",
            "description": "BI Top 5 2024 U.S. brokerage revenue",
            "value": f"{BI_TOP5_USD:.0f}",
            "unit": "USD",
            "origin": "RETRIEVED",
            "funded_by": "Business Insurance / Crain Communications (trade press; brokers self-report)",
            "url": "https://communityprod.blob.core.windows.net/public/top_100_2025_bi.pdf",
            "notes": "Marsh, Aon, Gallagher, WTW, Alliant. Revenue, not lives. P&C + benefits.",
        },
        {
            "line_id": "A2",
            "description": "BI Top 10 2024 U.S. brokerage revenue",
            "value": f"{BI_TOP10_USD:.0f}",
            "unit": "USD",
            "origin": "RETRIEVED",
            "funded_by": "Business Insurance / Crain Communications (trade press; brokers self-report)",
            "url": "https://communityprod.blob.core.windows.net/public/top_100_2025_bi.pdf",
            "notes": "Adds Brown & Brown, Hub, Lockton, AssuredPartners, USI.",
        },
        {
            "line_id": "A3",
            "description": "BI Top 100 2024 U.S. brokerage revenue (sum of published table)",
            "value": f"{BI_TOP100_USD:.0f}",
            "unit": "USD",
            "origin": "RETRIEVED",
            "funded_by": "Business Insurance / Crain Communications (trade press; brokers self-report)",
            "url": "https://communityprod.blob.core.windows.net/public/top_100_2025_bi.pdf",
            "notes": "Excludes firms with >49% personal-lines gross revenue. Not the entire US brokerage market.",
        },
        {
            "line_id": "A4",
            "description": "Top 5 / Top 100 U.S. brokerage revenue",
            "value": f"{BI_TOP5_PCT:.2f}",
            "unit": "percent of Top 100 revenue",
            "origin": "DERIVED",
            "funded_by": "same as A1–A3",
            "url": "https://communityprod.blob.core.windows.net/public/top_100_2025_bi.pdf",
            "notes": "A4 = A1 / A3. Not share of all US brokerage; remainder below #100 unknown.",
        },
        {
            "line_id": "A5",
            "description": "Top 10 / Top 100 U.S. brokerage revenue",
            "value": f"{BI_TOP10_PCT:.2f}",
            "unit": "percent of Top 100 revenue",
            "origin": "DERIVED",
            "funded_by": "same as A1–A3",
            "url": "https://communityprod.blob.core.windows.net/public/top_100_2025_bi.pdf",
            "notes": "A5 = A2 / A3 = 67.18%. Headline rounded to 67%.",
        },
        {
            "line_id": "A6",
            "description": "Marsh+Aon+Gallagher+WTW+Lockton / Top 100 (NFP inside Aon pro forma)",
            "value": f"{BI_NAMED_PCT:.2f}",
            "unit": "percent of Top 100 revenue",
            "origin": "DERIVED",
            "funded_by": "same as A1–A3",
            "url": "https://communityprod.blob.core.windows.net/public/top_100_2025_bi.pdf",
            "notes": "Named firms from the M2 pull list. NFP not separately ranked.",
        },
        {
            "line_id": "A7",
            "description": "MarshBerry citing BI: Top 10 share of Top 100, 2025 U.S. revenue vintage",
            "value": "70",
            "unit": "percent of Top 100 revenue",
            "origin": "RETRIEVED",
            "funded_by": "MarshBerry (broker M&A advisory thought leadership) citing Business Insurance",
            "url": "https://www.marshberry.com/resource/the-next-era-of-insurance-brokerage-the-top-100-defined-by-growth-consolidation-and-ai/",
            "notes": "They state Top 100 $83.3B and Top 10 $58.5B. Different year than A1–A6. Do not mix.",
        },
        {
            "line_id": "B1",
            "description": "PlanOptica top 5 published compensation shares (sum)",
            "value": f"{PO_TOP5_PCT:.1f}",
            "unit": "percent of PlanOptica H&W compensation universe",
            "origin": "DERIVED",
            "funded_by": "Underlying: plan sponsors filing Form 5500 with DOL/EBSA. Indexer: PlanOptica (for-profit).",
            "url": "https://planoptica.com/welfare/broker",
            "notes": "MMA 7.1 + Gallagher 5.9 + Lockton 5.8 + Mercer 5.0 + USI 4.3. Compensation, not lives.",
        },
        {
            "line_id": "B2",
            "description": "PlanOptica top 10 published compensation shares (sum)",
            "value": f"{PO_TOP10_PCT:.1f}",
            "unit": "percent of PlanOptica H&W compensation universe",
            "origin": "DERIVED",
            "funded_by": "Underlying: plan sponsors filing Form 5500 with DOL/EBSA. Indexer: PlanOptica (for-profit).",
            "url": "https://planoptica.com/welfare/broker",
            "notes": "Headline EH&B proxy. Adds WTW US 4.3 + Hub Midwest 4.1 + Aon Consulting 2.8 + Alliant 2.5 + B&B 2.2.",
        },
        {
            "line_id": "B3",
            "description": "PlanOptica remainder after top 10",
            "value": f"{PO_TAIL_PCT:.1f}",
            "unit": "percent of PlanOptica H&W compensation universe",
            "origin": "DERIVED",
            "funded_by": "same as B1",
            "url": "https://planoptica.com/welfare/broker",
            "notes": "B3 = 100 − B2. Table shows 43,129 broker names. Long tail, not a handful of doors.",
        },
        {
            "line_id": "B4",
            "description": "MMA + Mercer published shares (Marsh parent roll-up)",
            "value": f"{PO_MARSH_ROLLUP_PCT:.1f}",
            "unit": "percent of PlanOptica H&W compensation universe",
            "origin": "DERIVED",
            "funded_by": "same as B1",
            "url": "https://planoptica.com/welfare/broker",
            "notes": "PlanOptica lists MMA and Mercer separately. Parent roll-up is arithmetic, not a restated ranking.",
        },
        {
            "line_id": "B5",
            "description": "Named list Marsh+Gallagher+Lockton+WTW+Aon+NFP on PlanOptica shares",
            "value": f"{PO_NAMED_PCT:.1f}",
            "unit": "percent of PlanOptica H&W compensation universe",
            "origin": "DERIVED",
            "funded_by": "same as B1",
            "url": "https://planoptica.com/welfare/broker",
            "notes": "Uses B4 plus Gallagher 5.9, Lockton 5.8, WTW US 4.3, Aon Consulting 2.8, NFP 1.6. Entity splits understate parents.",
        },
        {
            "line_id": "C1",
            "description": "Marsh McLennan 2024 GAAP revenue",
            "value": f"{MMC_2024_REVENUE_USD:.0f}",
            "unit": "USD",
            "origin": "RETRIEVED",
            "funded_by": "Marsh McLennan (issuer 10-K / annual report)",
            "url": "https://www.corporate.marsh.com/web-assets/files-for-download/investors/2025/pdf-2024-marsh-mclennan-investors-annual-report.pdf",
            "notes": "Global. No US EH&B covered-lives figure.",
        },
        {
            "line_id": "C2",
            "description": "Mercer share of MMC 2024 revenue (approx.)",
            "value": f"{MMC_MERCER_PCT:.0f}",
            "unit": "percent of MMC revenue",
            "origin": "RETRIEVED",
            "funded_by": "Marsh McLennan (issuer)",
            "url": "https://www.corporate.marsh.com/web-assets/files-for-download/investors/2025/pdf-2024-marsh-mclennan-investors-annual-report.pdf",
            "notes": "Mercer includes Health + Wealth + Career. Health not broken out. Not lives.",
        },
        {
            "line_id": "C3",
            "description": "Aon Health Solutions 2024 revenue",
            "value": f"{AON_HEALTH_SOLUTIONS_2024_USD:.0f}",
            "unit": "USD",
            "origin": "RETRIEVED",
            "funded_by": "Aon plc (issuer earnings release / 10-K)",
            "url": "https://aon.mediaroom.com/2025-01-31-Aon-Reports-Fourth-Quarter-and-Full-Year-2024-Results",
            "notes": "Global. Includes consulting, brokerage, consumer benefits, talent, and NFP. Not US lives.",
        },
        {
            "line_id": "C4",
            "description": "WTW Health, Wealth & Career share of 2024 revenue",
            "value": f"{WTW_HWC_PCT:.0f}",
            "unit": "percent of WTW revenue",
            "origin": "RETRIEVED",
            "funded_by": "Willis Towers Watson (issuer 10-K)",
            "url": "https://www.sec.gov/Archives/edgar/data/1140536/000095017025026278/wtw-20241231.htm",
            "notes": "Health & Benefits described; no Health-only revenue and no covered lives.",
        },
        {
            "line_id": "C5",
            "description": "Gallagher U.S. share of brokerage + risk-management revenue, 2024",
            "value": f"{AJG_US_MIX_PCT:.0f}",
            "unit": "percent of AJG brokerage+RM revenue",
            "origin": "RETRIEVED",
            "funded_by": "Arthur J. Gallagher & Co. (issuer 10-K)",
            "url": "https://www.sec.gov/Archives/edgar/data/354190/000095017025021775/",
            "notes": "Geographic mix, not EH&B share and not lives. No benefits-line revenue breakout.",
        },
        {
            "line_id": "D1",
            "description": "U.S. small-group broker fees PMPM, 2024",
            "value": f"{KFF_SMALL_GROUP_PMPM:.2f}",
            "unit": "USD per member per month",
            "origin": "RETRIEVED",
            "funded_by": "KFF (nonprofit philanthropy, not Kaiser Permanente) analysis of Mark Farrah Associates Health Coverage Portal (commercial MLR database)",
            "url": "https://www.kff.org/health-costs/state-indicator/health-insurance-broker-compensation/",
            "notes": "Insurer-reported agent/broker fees + direct-sales costs ÷ member months. Not firm market share.",
        },
        {
            "line_id": "D2",
            "description": "U.S. large-group broker fees PMPM, 2024",
            "value": f"{KFF_LARGE_GROUP_PMPM:.2f}",
            "unit": "USD per member per month",
            "origin": "RETRIEVED",
            "funded_by": "same as D1",
            "url": "https://www.kff.org/health-costs/state-indicator/health-insurance-broker-compensation/",
            "notes": "Large-group PMPM is about one-third of small-group. Compensation rankings understate jumbo-account lives.",
        },
        {
            "line_id": "X2",
            "description": "Brokers below BI Top 100 + personal-lines-majority firms",
            "value": "",
            "unit": "USD / lives",
            "origin": "NOT RETRIEVED",
            "funded_by": "n/a",
            "url": "https://communityprod.blob.core.windows.net/public/top_100_2025_bi.pdf",
            "notes": "A4–A6 denominators are Top 100, not the market. Unknown remainder.",
        },
        {
            "line_id": "X3",
            "description": "Spectrum-state cut of any concentration figure",
            "value": "",
            "unit": "percent",
            "origin": "NOT RETRIEVED",
            "funded_by": "n/a",
            "url": "",
            "notes": "M2 geography is 'same as M1'. Public rankings are US. No conversion invented.",
        },
        {
            "line_id": "X4",
            "description": "Welfare plans / small employers that do not file Form 5500 Schedule A as used here",
            "value": "",
            "unit": "lives / compensation",
            "origin": "NOT RETRIEVED",
            "funded_by": "n/a",
            "url": "https://planoptica.com/freeerisa",
            "notes": "ERISA welfare filings miss a large small-employer slice; jumbo consulting fees paid off Schedule A also miss.",
        },
    ]

    write_csv(
        OUT / "assumption_register.csv",
        ["line_id", "description", "value", "unit", "origin", "funded_by", "url", "notes"],
        register,
    )

    summary = {
        "verdict": "valid-with-caveats",
        "metric_id": "M2",
        "definition": {
            "numerator": "covered lives at the top N broker firms (e.g. top 5 / top 10)",
            "denominator": "total broker-placed covered lives in the same geography (M1 / Spectrum states)",
            "unit": "percent",
            "gate": "Whether a few national brokers can move volume or the channel is fragmented",
        },
        "lives_share_pct": None,
        "headline_proxy": {
            "label": "PlanOptica top 10 share of US health-and-welfare Form 5500 compensation",
            "value_pct": PO_TOP10_PCT,
            "unit": "percent of compensation, not lives",
            "line_id": "B2",
        },
        "bi_2024": {
            "top5_usd": BI_TOP5_USD,
            "top10_usd": BI_TOP10_USD,
            "top100_usd": BI_TOP100_USD,
            "top5_pct_of_top100": round(BI_TOP5_PCT, 2),
            "top10_pct_of_top100": round(BI_TOP10_PCT, 2),
            "named_marsh_aon_ajg_wtw_lockton_pct_of_top100": round(BI_NAMED_PCT, 2),
        },
        "planoptica": {
            "top5_pct": PO_TOP5_PCT,
            "top10_pct": PO_TOP10_PCT,
            "tail_pct": PO_TAIL_PCT,
            "marsh_mma_plus_mercer_pct": PO_MARSH_ROLLUP_PCT,
            "named_list_pct": PO_NAMED_PCT,
            "broker_names_on_table": PO_BROKER_COUNT,
            "implied_universe_from_mma_share_usd": round(PO_IMPLIED_TOTAL_USD),
            "top10_pct_from_dollars_check": round(PO_TOP10_PCT_FROM_DOLLARS, 1),
        },
        "marshberry_2025_vintage": {
            "top100_usd": MARSHBERRY_TOP100_USD,
            "top10_usd": MARSHBERRY_TOP10_USD,
            "top10_pct_stated": 70,
        },
        "ten_k": {
            "mmc_2024_revenue_usd": MMC_2024_REVENUE_USD,
            "mercer_pct_of_mmc": MMC_MERCER_PCT,
            "aon_health_solutions_2024_usd": AON_HEALTH_SOLUTIONS_2024_USD,
            "wtw_hwc_pct": WTW_HWC_PCT,
            "ajg_us_mix_pct": AJG_US_MIX_PCT,
            "covered_lives_disclosed": False,
        },
        "kff_pmpm_2024": {
            "small_group": KFF_SMALL_GROUP_PMPM,
            "large_group": KFF_LARGE_GROUP_PMPM,
        },
        "unknown_remainder": [
            "Specified covered-lives share (X1)",
            "Brokers below BI Top 100 and personal-lines-majority firms (X2)",
            "Spectrum-state geography (X3)",
            "Non-filers and off-Schedule-A jumbo consulting fees (X4)",
            "Sister-entity undercount on Form 5500 names",
        ],
        "changes_go_no_go": (
            "Yes as channel architecture (few national doors vs a long tail), "
            "not as a product launch decision. The EH&B compensation proxy says "
            "top 10 hold a minority (44%) of observed compensation, so a handful "
            "of national partnerships does not cover the book. Lives share still unknown."
        ),
    }
    (OUT / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print("BI top5 % of top100", round(BI_TOP5_PCT, 2))
    print("BI top10 % of top100", round(BI_TOP10_PCT, 2))
    print("BI named % of top100", round(BI_NAMED_PCT, 2))
    print("BI top100 USD", BI_TOP100_USD)
    print("PO top5", PO_TOP5_PCT, "top10", PO_TOP10_PCT, "tail", PO_TAIL_PCT)
    print("PO named", PO_NAMED_PCT, "Marsh rollup", PO_MARSH_ROLLUP_PCT)
    print("dollar check top10 %", round(PO_TOP10_PCT_FROM_DOLLARS, 1))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
